//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReport.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResultSummaryDto", Namespace="http://schemas.datacontract.org/2004/07/Synevo.Data.Dto")]
    [System.SerializableAttribute()]
    public partial class OrderResultSummaryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebReport.ServiceReference.OrderResultDetailDto[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ResultsDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinal {
            get {
                return this.IsFinalField;
            }
            set {
                if ((this.IsFinalField.Equals(value) != true)) {
                    this.IsFinalField = value;
                    this.RaisePropertyChanged("IsFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportName {
            get {
                return this.ReportNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportNameField, value) != true)) {
                    this.ReportNameField = value;
                    this.RaisePropertyChanged("ReportName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebReport.ServiceReference.OrderResultDetailDto[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ResultsDate {
            get {
                return this.ResultsDateField;
            }
            set {
                if ((this.ResultsDateField.Equals(value) != true)) {
                    this.ResultsDateField = value;
                    this.RaisePropertyChanged("ResultsDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResultDetailDto", Namespace="http://schemas.datacontract.org/2004/07/Synevo.Data.Dto")]
    [System.SerializableAttribute()]
    public partial class OrderResultDetailDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdfNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ServiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebReport.ServiceReference.OrderResultType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidatorEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderName {
            get {
                return this.FolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderNameField, value) != true)) {
                    this.FolderNameField = value;
                    this.RaisePropertyChanged("FolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdfName {
            get {
                return this.PdfNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfNameField, value) != true)) {
                    this.PdfNameField = value;
                    this.RaisePropertyChanged("PdfName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCd {
            get {
                return this.ServiceCdField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCdField, value) != true)) {
                    this.ServiceCdField = value;
                    this.RaisePropertyChanged("ServiceCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ServiceId {
            get {
                return this.ServiceIdField;
            }
            set {
                if ((this.ServiceIdField.Equals(value) != true)) {
                    this.ServiceIdField = value;
                    this.RaisePropertyChanged("ServiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceUri {
            get {
                return this.ServiceUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceUriField, value) != true)) {
                    this.ServiceUriField = value;
                    this.RaisePropertyChanged("ServiceUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebReport.ServiceReference.OrderResultType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidatorEmail {
            get {
                return this.ValidatorEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidatorEmailField, value) != true)) {
                    this.ValidatorEmailField = value;
                    this.RaisePropertyChanged("ValidatorEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResultType", Namespace="http://schemas.datacontract.org/2004/07/Synevo.Data.Dto")]
    public enum OrderResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SilabMainResult = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SilabMicroResult = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExtraAttachment = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://synevo.ua/integration/silab", ConfigurationName="ServiceReference.IResultService")]
    public interface IResultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://synevo.ua/integration/silab/IResultService/GetResultSummary", ReplyAction="http://synevo.ua/integration/silab/IResultService/GetResultSummaryResponse")]
        WebReport.ServiceReference.OrderResultSummaryDto GetResultSummary(long orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://synevo.ua/integration/silab/IResultService/GetResultSummary", ReplyAction="http://synevo.ua/integration/silab/IResultService/GetResultSummaryResponse")]
        System.Threading.Tasks.Task<WebReport.ServiceReference.OrderResultSummaryDto> GetResultSummaryAsync(long orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://synevo.ua/integration/silab/IResultService/GetResultSummaryByWebCode", ReplyAction="http://synevo.ua/integration/silab/IResultService/GetResultSummaryByWebCodeRespon" +
            "se")]
        WebReport.ServiceReference.OrderResultSummaryDto GetResultSummaryByWebCode(string webAccessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://synevo.ua/integration/silab/IResultService/GetResultSummaryByWebCode", ReplyAction="http://synevo.ua/integration/silab/IResultService/GetResultSummaryByWebCodeRespon" +
            "se")]
        System.Threading.Tasks.Task<WebReport.ServiceReference.OrderResultSummaryDto> GetResultSummaryByWebCodeAsync(string webAccessCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResultServiceChannel : WebReport.ServiceReference.IResultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultServiceClient : System.ServiceModel.ClientBase<WebReport.ServiceReference.IResultService>, WebReport.ServiceReference.IResultService {
        
        public ResultServiceClient() {
        }
        
        public ResultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebReport.ServiceReference.OrderResultSummaryDto GetResultSummary(long orderId) {
            return base.Channel.GetResultSummary(orderId);
        }
        
        public System.Threading.Tasks.Task<WebReport.ServiceReference.OrderResultSummaryDto> GetResultSummaryAsync(long orderId) {
            return base.Channel.GetResultSummaryAsync(orderId);
        }
        
        public WebReport.ServiceReference.OrderResultSummaryDto GetResultSummaryByWebCode(string webAccessCode) {
            return base.Channel.GetResultSummaryByWebCode(webAccessCode);
        }
        
        public System.Threading.Tasks.Task<WebReport.ServiceReference.OrderResultSummaryDto> GetResultSummaryByWebCodeAsync(string webAccessCode) {
            return base.Channel.GetResultSummaryByWebCodeAsync(webAccessCode);
        }
    }
}
